---
site:
  title: "Writing your first playbook"
  url: https://github.com/redhat-gpte-devopsautomation/zt-writing-your-first-playbook
  start_page: modules::01-playbook-inventory.adoc

asciidoc:
  attributes:
    lab_name: "I'm the lab_name var"
    release-version: master
    page-pagination: true
    my_var: "foo - this is an asciidoc attribute from `site.yml`"

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
