---
containers: []
virtualmachines:
  - name: "host1"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
        #cloud-config
        user: rhel
        password: ansible123!
        chpasswd: { expire: False }
        ssh_pwauth: true
  - name: "node1"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
        #cloud-config
        user: rhel
        password: ansible123!
        chpasswd: { expire: False }
        ssh_pwauth: true
  - name: "node2"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
        #cloud-config
        user: rhel
        password: ansible123!
        chpasswd: { expire: False }
        ssh_pwauth: true
  - name: "node3"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
        #cloud-config
        user: rhel
        password: ansible123!
        chpasswd: { expire: False }
        ssh_pwauth: true
