---
containers: []
virtualmachines:
  - name: "host1"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
  - name: "node1"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
  - name: "node2"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
  - name: "node3"
    image: "rhel-9.5"
    memory: "8G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
      - secondary
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
        - systemctl reload sshd
